include: package:lints/recommended.yaml

linter:
  rules:
    camel_case_types: true
    prefer_final_fields: true
    prefer_final_locals: true
    non_constant_identifier_names: false
    constant_identifier_names: false

analyzer:
#   exclude:
#     - path/to/excluded/files/**
